# Generated by Django 5.0.1 on 2024-02-05 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('user_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, null=True)),
                ('lang_code', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LangsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_in', models.CharField(max_length=15, unique=True)),
                ('lang_out', models.CharField(max_length=15, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('blocked', 'BLOCKED'), ('other', 'OTHER')], max_length=20)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='UserLangs',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eeforeign_key', serialize=False, to='bot.accounts')),
                ('tts', models.BooleanField(default=True)),
                ('in_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birinci_foreign_key', to='bot.langslist', to_field='lang_in')),
                ('out_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ikkinchi_foreign_key', to='bot.langslist', to_field='lang_out')),
            ],
        ),
    ]
